export enum EventType {
  CREATE_SHAPE = "CREATE_SHAPE",
  DELETE_SHAPE = "DELETE_SHAPE",
  MOVE_SHAPE = "MOVE_SHAPE",
  ROTATE_SHAPE = "ROTATE_SHAPE",
  SCALE_SHAPE = "SCALE_SHAPE",
  CHANGE_FILL = "CHANGE_FILL",
  CHANGE_STROKE = "CHANGE_STROKE",
  CHANGE_LAYER = "CHANGE_LAYER",
  CHANGE_TEXT = "CHANGE_TEXT",
  ADD_IMAGE = "ADD_IMAGE"
}